default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  database: trelloverse_development

test:
  <<: *default
  database: trelloverse_test

production:
  <<: *default
